spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=portfolio_user
spring.datasource.password=portfolio_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=backend
